export const pakistanCities = [
  "Abbottabad",
  "Attock",
  "Bahawalpur",
  "Bahawalnagar",
  "Burewala",
  "Chakwal",
  "Chiniot",
  "Dadu",
  "Dera Ghazi Khan",
  "Dera Ismail Khan",
  "Faisalabad",
  "Ghotki",
  "Gujranwala",
  "Gujrat",
  "Hafizabad",
  "Haripur",
  "Hyderabad",
  "Islamabad",
  "Jacobabad",
  "Jhelum",
  "Jhang",
  "Karachi",
  "Kasur",
  "Khairpur",
  "Khanewal",
  "Khuzdar",
  "Kohat",
  "Lahore",
  "Larkana",
  "Layyah",
  "Lodhran",
  "Mardan",
  "Mandi Bahauddin",
  "Mirpur Khas",
  "Multan",
  "Muzaffargarh",
  "Nawabshah",
  "Okara",
  "Peshawar",
  "Quetta",
  "Rahim Yar Khan",
  "Rawalpindi",
  "Sahiwal",
  "Sargodha",
  "Sheikhupura",
  "Shikarpur",
  "Sialkot",
  "Sukkur",
  "Swat",
  "Toba Tek Singh",
  "Vehari",
  "Wah Cantt",
  "Wazirabad",
].sort();
